// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAThtL3FG5oSY1_-DQq6cvod0T463-Nwlc',
    appId: '1:590751786816:web:cc6dbbc1feb8e65dda7ca5',
    messagingSenderId: '590751786816',
    projectId: 'iti-final-project0',
    authDomain: 'iti-final-project0.firebaseapp.com',
    storageBucket: 'iti-final-project0.appspot.com',
    measurementId: 'G-5N6JRTD2XG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJ6tojrT0tghiG-JLww6keQNlmQs2lPtg',
    appId: '1:590751786816:android:6e80cfbea1092aecda7ca5',
    messagingSenderId: '590751786816',
    projectId: 'iti-final-project0',
    storageBucket: 'iti-final-project0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA96y54lxISs282tfmQogUeduXavQyZPlM',
    appId: '1:590751786816:ios:373ed59f5e2871a2da7ca5',
    messagingSenderId: '590751786816',
    projectId: 'iti-final-project0',
    storageBucket: 'iti-final-project0.appspot.com',
    iosClientId: '590751786816-8vnief8dmoakeicpruv4p7bd39i151ie.apps.googleusercontent.com',
    iosBundleId: 'com.example.jumia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA96y54lxISs282tfmQogUeduXavQyZPlM',
    appId: '1:590751786816:ios:9199eecf8ac24a8fda7ca5',
    messagingSenderId: '590751786816',
    projectId: 'iti-final-project0',
    storageBucket: 'iti-final-project0.appspot.com',
    iosClientId: '590751786816-022kqv8258vc5rn9hti3c0ir5s4jkvq7.apps.googleusercontent.com',
    iosBundleId: 'com.example.jumia.RunnerTests',
  );
}
